service: backend-proposal-v2

provider:
  name: aws
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: us-east-1

S3PublicData:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: techco-public-data
    AccessControl: PublicRead
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: error.html
    CorsConfiguration:
      CorsRules:
        - AllowedHeaders:
            - '*'
          AllowedMethods:
            - GET
          AllowedOrigins:
            - '*'
          MaxAge: 3000
    Tags:
      - Key: Environment
        Value: ${self:provider.stage}
      - Key: Name
        Value: techco-public-data

S3PublicDataPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref S3PublicData
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: !Join 
            - ''
            - - 'arn:aws:s3:::'
              - !Ref S3PublicData
              - '/*'