from src.domain.assistant import ASSISTANT_TYPE

ASSISTANTS_IDS = {
    ASSISTANT_TYPE.TECHNICAL_ASSESSMENT_ASSISTANT: "asst_GnABLX5xOYOgGx46otPahM8e",
    ASSISTANT_TYPE.SOFT_ASSESSMENT_ASSISTANT: "asst_8KKSQIlMNjFq0YvscV5a492u",
}
