WebSocketConnections:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: connection_id
        AttributeType: S
    KeySchema:
      - AttributeName: connection_id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: user_id_index
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
    TableName: ${self:provider.stage}-websocket-connections
    TimeToLiveSpecification:
        AttributeName: "expires_at"
        Enabled: true

WebSocketConnectionsPublic:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: hiring_process_id
        AttributeType: S
      - AttributeName: connection_id
        AttributeType: S
    KeySchema:
      - AttributeName: connection_id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: hiring_process_id_index
        KeySchema:
          - AttributeName: hiring_process_id
            KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
    TableName: ${self:provider.stage}-websocket-connections-public
    TimeToLiveSpecification:
        AttributeName: "expires_at"
        Enabled: true

FileProcessingStatus:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-file-processing-status
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: process_id
            AttributeType: S
        KeySchema:
          - AttributeName: process_id
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expires_at
          Enabled: true
