WebSocketConnections:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: connection_id
        AttributeType: S
    KeySchema:
      - AttributeName: connection_id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: user_id_index
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
    TableName: ${self:provider.stage}-websocket-connections
    TimeToLiveSpecification:
        AttributeName: "expires_at"
        Enabled: true
