from src.domain.position_configuration import PHASE_TYPE
from src.domain.assistant import ASSISTANT_TYPE

HOMOLOGATE_POSITION_CONFIGURATION_AND_ASSISTAND = {
    PHASE_TYPE.DESCRIPTION: ASSISTANT_TYPE.POSITION_ASSISTANT,
    PHASE_TYPE.TECHNICAL_TEST: ASSISTANT_TYPE.TECHNICAL_ASSESSMENT_ASSISTANT,
}